using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QSO_Trainer.Lister
{
 public   class Citys
    {
        public static List<string> City = new List<string>(new string[] {
            "valley",
            "valley",
            "valley",
            "alexandria",
            "alexandria",//5
            "alexandria",
            "boulder",
            "boulder",
            "boulder",
            "lewiston",//10
            "lewiston",
            "lewiston",
            "lexington",
            "lexington",
            "lexington",//15
            "crossville",
            "crossville",
            "crossville",
            "lakeland",
            "lakeland",//20
            "lakeland",
            "wichita",
            "wichita",
            "wichita",
            "hagerstown",//25
            "hagerstown",
            "hagerstown",
            "aberdeen",
            "aberdeen",
            "aberdeen",//30
            "kalamazoo",
            "kalamazoo",
            "kalamazoo",
            "kankakee",
            "kankakee",//35
            "kankakee",
            "kailua",
            "kailua",
            "kailua",
            "lakeland",//40
            "lakeland",
            "lakeland",
            "aberdeen",
            "aberdeen",
            "aberdeen",//45
            "charleston",
            "charleston",
            "charleston",
            "pocatello",
            "pocatello",//50
            "pocatello",
            "lexington",
            "lexington",
            "lexington",
            "huntsville",//55
            "huntsville",
            "huntsville",
            "alamogordo",
            "alamogordo",
            "alamogordo",//60
            "provo",
            "provo",
            "provo",
            "hibbing",
            "hibbing",//65
            "hibbing",
            "pittsfield",
            "pittsfield",
            "pittsfield",
            "rutland",//70
            "rutland",
            "rutland",
            "fairbanks",
            "fairbanks",
            "fairbanks",//75
            "muskogee",
            "muskogee",
            "muskogee",
            "spokane",
            "spokane",//80
            "spokane",
            "charleston",
            "charleston",
            "charleston",
            "muncie",//85
            "muncie",
            "muncie",
            "pawtucket",
            "pawtucket",
            "pawtucket",//90
            "akron",
            "akron",
            "akron",
            "huntsville",
            "huntsville",//95
            "huntsville",
            "pittsfield",
            "pittsfield",
            "pittsfield",
            "alamogordo",//100
            "alamogordo",
            "alamogordo",
            "bismarck",
            "bismarck",
            "bismarck",//105
            "kalamazoo",
            "kalamazoo",
            "kalamazoo",
            "lexington",
            "lexington",//110
            "lexington",
            "hibbing",
            "hibbing",
            "hibbing",
            "kirksville",//115
            "kirksville",
            "kirksville",
            "muncie",
            "muncie",
            "muncie",//120
            "pittsfield",
            "pittsfield",
            "pittsfield",
            "harlingen",
            "harlingen",//125
            "harlingen",
            "fairbanks",
            "fairbanks",
            "fairbanks",
            "jackson",//130
            "jackson",
            "jackson",
            "harlingen",
            "harlingen",
            "harlingen",//135
            "kirksville",
            "kirksville",
            "kirksville",
            "kalamazoo",
            "kalamazoo",//140
            "kalamazoo",
            "lynchburg",
            "lynchburg",
            "lynchburg",
            "hanna",//145
            "hanna",
            "hanna",
            "augusta",
            "augusta",
            "augusta",//150
            "provo",
            "provo",
            "provo",
            "hanna",
            "hanna",//155
            "hanna",
            "alamogordo",
            "alamogordo",
            "alamogordo",
            "alexandria",//160
            "alexandria",
            "alexandria",
            "davenport",
            "davenport",
            "davenport",//165
            "crossville",
            "crossville",
            "crossville",
            "fairbanks",
            "fairbanks",//170
            "fairbanks",
            "jackson",
            "jackson",
            "jackson",
            "altoona",//175
            "altoona",
            "altoona",
            "kankakee",
            "kankakee",
            "kankakee",//180
            "crossville",
            "crossville",
            "crossville",
            "utica",
            "utica",//185
            "utica",
            "kankakee",
            "kankakee",
            "kankakee",
            "winnemucca",//190
            "winnemucca",
            "winnemucca",
            "pawtucket",
            "pawtucket",
            "pawtucket",//195
            "boulder",
            "boulder",
            "boulder",
            "crossville",
            "crossville",//200
            "crossville",
            "lewiston",
            "lewiston",
            "lewiston",
            "rutland",//205
            "rutland",
            "rutland",
            "oshkosh",
            "oshkosh",
            "oshkosh",//210
            "altoona",
            "altoona",
            "altoona",
            "altoona",
            "altoona",//215
            "altoona",
            "utica",
            "utica",
            "utica",
            "hanna",//220
            "hanna",
            "hanna",
            "kankakee",
            "kankakee",
            "kankakee",//225
            "morgantown",
            "morgantown",
            "morgantown",
            "dover",
            "dover",//230
            "dover",
            "hanna",
            "hanna",
            "hanna",
            "pawtucket",//235
            "pawtucket",
            "pawtucket",
            "danbury",
            "danbury",
            "danbury",//240
            "jackson",
            "jackson",
            "jackson",
            "lewiston",
            "lewiston",//245
            "lewiston",
            "fayetteville",
            "fayetteville",
            "fayetteville",
            "aberdeen",//250
            "aberdeen",
            "aberdeen",
            "provo",
            "provo",
            "provo",//255
            "boulder",
            "boulder",
            "boulder",
            "fayetteville",
            "fayetteville",//260
            "fayetteville",
            "kalamazoo",
            "kalamazoo",
            "kalamazoo",
            "kirksville",//265
            "kirksville",
            "kirksville",
            "spokane",
            "spokane",
            "spokane",//270
            "grants pass",
            "grants pass",
            "grants pass",
            "provo",
            "provo",//275
            "provo",
            "alexandria",
            "alexandria",
            "alexandria",
            "alexandria",//280
            "alexandria",
            "alexandria",
            "morgantown",
            "morgantown",
            "morgantown",//285
            "kitty hawk",
            "kitty hawk",
            "kitty hawk",
            "kankakee",
            "kankakee",//290
            "kankakee",
            "akron",
            "akron",
            "akron",
            "provo",//295
            "provo",
            "provo",
            "phoenix",
            "phoenix",
            "phoenix",//300
            "fairbanks",
            "fairbanks",
            "fairbanks",
            "hibbing",
            "hibbing",//305
            "hibbing",
            "alamogordo",
            "alamogordo",
            "alamogordo",
            "fayetteville",//310
            "fayetteville",
            "fayetteville",
            "aberdeen",
            "aberdeen",
            "aberdeen",//315
            "kitty hawk",
            "kitty hawk",
            "kitty hawk",
            "pocatello",
            "pocatello",//320
            "pocatello",
            "fayetteville",
            "fayetteville",
            "fayetteville",
            "provo",//325
            "provo",
            "provo",
            "alamogordo",
            "alamogordo",
            "alamogordo",//330
            "augusta",
            "augusta",
            "augusta",
            "alamogordo",
            "alamogordo",//335
            "alamogordo",
            "bismarck",
            "bismarck",
            "bismarck",
            "kailua",//340
            "kailua",
            "kailua",
            "lewiston",
            "lewiston",
            "lewiston",//345
            "newark",
            "newark",
            "newark",
            "pittsfield",
            "pittsfield",//350
            "pittsfield",
            "kailua",
            "kailua",
            "kailua",
            "winnemucca",//355
            "winnemucca",
            "winnemucca",
            "akron",
            "akron",
            "akron",//360
            "jackson",
            "jackson",
            "jackson",
            "utica",
            "utica",//365
            "utica",
            "hagerstown",
            "hagerstown",
            "hagerstown",
            "davenport",//370
            "davenport",
            "davenport",
            "hanna",
            "hanna",
            "hanna",//375
            "spokane",
            "spokane",
            "spokane",
            "harlingen",
            "harlingen",//380
            "harlingen",
            "hibbing",
            "hibbing",
            "hibbing",
            "alamogordo",//385
            "alamogordo",
            "alamogordo",
            "fairbanks",
            "fairbanks",
            "fairbanks",//390
            "pocatello",
            "pocatello",
            "pocatello",
            "phoenix",
            "phoenix",//395
            "phoenix",
            "wichita",
            "wichita",
            "wichita",
            "huntsville",//400
            "huntsville",
            "huntsville",
            "winnemucca",
            "winnemucca",
            "winnemucca",//405
            "valley",
            "valley",
            "valley",
            "boulder",
            "boulder",//410
            "boulder",
            "augusta",
            "augusta",
            "augusta",
            "davenport",//415
            "davenport",
            "davenport",
            "grants pass",
            "grants pass",
            "grants pass",//420
            "charleston",
            "charleston",
            "charleston",
            "grants pass",
            "grants pass",//425
            "grants pass",
            "crossville",
            "crossville",
            "crossville",
            "provo",//430
            "provo",
            "provo",
            "hibbing",
            "hibbing",
            "hibbing",//435
            "kalamazoo",
            "kalamazoo",
            "kalamazoo",
            "spokane",
            "spokane",//440
            "spokane",
            "bismarck",
            "bismarck",
            "bismarck",
            "kitty hawk",//445
            "kitty hawk",
            "kitty hawk",
            "kirksville",
            "kirksville",
            "kirksville",//450
            "utica",
            "utica",
            "utica",
            "charleston",
            "charleston",//455
            "charleston",
            "augusta",
            "augusta",
            "augusta",
            "alamogordo",//460
            "alamogordo",
            "alamogordo",
            "hibbing",
            "hibbing",
            "hibbing",//465
            "rutland",
            "rutland",
            "rutland",
            "newark",
            "newark",//470
            "newark",
            "altoona",
            "altoona",
            "altoona",
            "wichita",//475
            "wichita",
            "wichita",
            "alliance",
            "alliance",
            "alliance",//480
            "pittsfield",
            "pittsfield",
            "pittsfield",
            "spokane",
            "spokane",//485
            "spokane",
            "nashua",
            "nashua",
            "nashua",
            "aberdeen",//490
            "aberdeen",
            "aberdeen",
            "harlingen",
            "harlingen",
            "harlingen",//495
            "bozeman",
            "bozeman",
            "bozeman",
            "wichita",
            "wichita",//500
            "wichita",
            "lakeland",
            "lakeland",
            "lakeland",
            "hanna",//505
            "hanna",
            "hanna",
            "nashua",
            "nashua",
            "nashua",//510
            "lynchburg",
            "lynchburg",
            "lynchburg",
            "kalamazoo",
            "kalamazoo",//515
            "kalamazoo",
            "nashua",
            "nashua",
            "nashua",
            "bismarck",//520
            "bismarck",
            "bismarck",
            "davenport",
            "davenport",
            "davenport",//525
            "provo",
            "provo",
            "provo",
            "hagerstown",
            "hagerstown",//530
            "hagerstown",
            "nashua",
            "nashua",
            "nashua",
            "aberdeen",//535
            "aberdeen",
            "aberdeen",
            "dover",
            "dover",
            "dover",//540
            "huntsville",
            "huntsville",
            "huntsville",
            "bozeman",
            "bozeman",//545
            "bozeman",
            "spokane",
            "spokane",
            "spokane",
            "crossville",//550
            "crossville",
            "crossville",
            "augusta",
            "augusta",
            "augusta",//555
            "dover",
            "dover",
            "dover",
            "utica",
            "utica",//560
            "utica",
            "hibbing",
            "hibbing",
            "hibbing",
            "pittsfield",//565
            "pittsfield",
            "pittsfield",
            "nashua",
            "nashua",
            "nashua",//570
            "provo",
            "provo",
            "provo",
            "newark",
            "newark",//575
            "newark",
            "jackson",
            "jackson",
            "jackson",
            "lynchburg",//580
            "lynchburg",
            "lynchburg",
            "hagerstown",
            "hagerstown",
            "hagerstown",//585
            "alliance",
            "alliance",
            "alliance",
            "danbury",
            "danbury",//590
            "danbury",
            "oshkosh",
            "oshkosh",
            "oshkosh",
            "grass valley",//595
            "grass valley",
            "grass valley",
            "hibbing",
            "hibbing",
            "hibbing",//600
            "spokane",
            "spokane",
            "spokane",
            "provo",
            "provo",//605
            "provo",
            "kitty hawk",
            "kitty hawk",
            "kitty hawk",
            "oshkosh",//610
            "oshkosh",
            "oshkosh",
            "alexandria",
            "alexandria",
            "alexandria",//615
            "spokane",
            "spokane",
            "spokane",
            "alexandria",
            "alexandria",//620
            "alexandria",
            "danbury",
            "danbury",
            "danbury",
            "aberdeen",//625
            "aberdeen",
            "aberdeen",
            "charleston",
            "charleston",
            "charleston",//630
            "alamogordo",
            "alamogordo",
            "alamogordo",
            "crossville",
            "crossville",//635
            "crossville",
            "lynchburg",
            "lynchburg",
            "lynchburg",
            "boulder",//640
            "boulder",
            "boulder",
            "kalamazoo",
            "kalamazoo",
            "kalamazoo",//645
            "crossville",
            "crossville",
            "crossville",
            "newark",
            "newark",//650
            "newark",
            "harlingen",
            "harlingen",
            "harlingen",
            "lewiston",//655
            "lewiston",
            "lewiston",
            "bozeman",
            "bozeman",
            "bozeman",//660
            "lexington",
            "lexington",
            "lexington",
            "pittsfield",
            "pittsfield",//665
            "pittsfield",
            "augusta",
            "augusta",
            "augusta",
            "huntsville",//670
            "huntsville",
            "huntsville",
            "utica",
            "utica",
            "utica",//675
            "spokane",
            "spokane",
            "spokane",
            "utica",
            "utica",//680
            "utica",
            "huntsville",
            "huntsville",
            "huntsville",
            "kailua",//685
            "kailua",
            "kailua",
            "kankakee",
            "kankakee",
            "kankakee",//690
            "winnemucca",
            "winnemucca",
            "winnemucca",
            "fayetteville",
            "fayetteville",//695
            "fayetteville",
            "pocatello",
            "pocatello",
            "pocatello",
            "hibbing",//700
            "hibbing",
            "hibbing",
            "phoenix",
            "phoenix",
            "phoenix",//705
            "boulder",
            "boulder",
            "boulder",
            "jackson",
            "jackson",//710
            "jackson",
            "winnemucca",
            "winnemucca",
            "winnemucca",
            "utica",//715
            "utica",
            "utica",
            "davenport",
            "davenport",
            "davenport",//720
            "hagerstown",
            "hagerstown",
            "hagerstown",
            "nashua",
            "nashua",//725
            "nashua",
            "davenport",
            "davenport",
            "davenport",
            "alexandria",//730
            "alexandria",
            "alexandria",
            "nashua",
            "nashua",
            "nashua",//735
            "davenport",
            "davenport",
            "davenport",
            "morgantown",
            "morgantown",//740
            "morgantown",
            "alexandria",
            "alexandria",
            "alexandria",
            "nashua",//745
            "nashua",
            "nashua",
            "kalamazoo",
            "kalamazoo",
            "kalamazoo",//750
            "dover",
            "dover",
            "dover",
            "wichita",
            "wichita",//755
            "wichita",
            "kirksville",
            "kirksville",
            "kirksville",
            "nashua",//760
            "nashua",
            "nashua",
            "lynchburg",
            "lynchburg",
            "lynchburg",//765
            "bozeman",
            "bozeman",
            "bozeman",
            "kitty hawk",
            "kitty hawk",//770
            "kitty hawk",
            "pawtucket",
            "pawtucket",
            "pawtucket",
            "davenport",//775
            "davenport",
            "davenport",
            "hagerstown",
            "hagerstown",
            "hagerstown",//780
            "grants pass",
            "grants pass",
            "grants pass",
            "harlingen",
            "harlingen",//785
            "harlingen",
            "newark",
            "newark",
            "newark",
            "kalamazoo",//790
            "kalamazoo",
            "kalamazoo",
            "davenport",
            "davenport",
            "davenport",//795
            "spokane",
            "spokane",
            "spokane",
            "newark",
            "newark",//800
            "newark",
            "fairbanks",
            "fairbanks",
            "fairbanks",
            "hagerstown",//805
            "hagerstown",
            "hagerstown",
            "charleston",
            "charleston",
            "charleston",//810
            "charleston",
            "charleston",
            "charleston",
            "davenport",
            "davenport",//815
            "davenport",
            "morgantown",
            "morgantown",
            "morgantown",
            "winnemucca",//820
            "winnemucca",
            "winnemucca",
            "augusta",
            "augusta",
            "augusta",//825
            "hanna",
            "hanna",
            "hanna",
            "phoenix",
            "phoenix",//830
            "phoenix",
            "phoenix",
            "phoenix",
            "phoenix",
            "lexington",//835
            "lexington",
            "lexington",
            "kirksville",
            "kirksville",
            "kirksville",//840
            "augusta",
            "augusta",
            "augusta",
            "kailua",
            "kailua",//845
            "kailua",
            "kitty hawk",
            "kitty hawk",
            "kitty hawk",
            "dover",//850
            "dover",
            "dover",
            "bismarck",
            "bismarck",
            "bismarck",//855
            "morgantown",
            "morgantown",
            "morgantown",
            "kankakee",
            "kankakee",//860
            "kankakee",
            "kitty hawk",
            "kitty hawk",
            "kitty hawk",
            "fayetteville",//865
            "fayetteville",
            "fayetteville",
            "lakeland",
            "lakeland",
            "lakeland",//870
            "danbury",
            "danbury",
            "danbury",
            "aberdeen",
            "aberdeen",//875
            "aberdeen",
            "spokane",
            "spokane",
            "spokane",
            "jackson",//880
            "jackson",
            "jackson",
            "aberdeen",
            "aberdeen",
            "aberdeen",//885
            "winnemucca",
            "winnemucca",
            "winnemucca",
            "fairbanks",
            "fairbanks",//890
            "fairbanks",
            "lexington",
            "lexington",
            "lexington",
            "fayetteville",//895
            "fayetteville",
            "fayetteville",
            "kalamazoo",
            "kalamazoo",
            "kalamazoo"//900
        });

    }
}
