using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QSO_Trainer.Lister
{
public    class Occupations
    {
        public static List<string> Occupation = new List<string>(new string[] {
            "programmer",
            "programmer",
            "programmer",
            "lawyer",
            "lawyer",//5
            "lawyer",
            "lawyer",
            "lawyer",
            "lawyer",
            "bookkeeper",//10
            "bookkeeper",
            "bookkeeper",
            "engineer",
            "engineer",
            "engineer",//15
            "student",
            "student",
            "student",
            "chemist",
            "chemist",//20
            "chemist",
            "lawyer",
            "lawyer",
            "lawyer",
            "bookkeeper",//25
            "bookkeeper",
            "bookkeeper",
            "doctor",
            "doctor",
            "doctor",//30
            "carpenter",
            "carpenter",
            "carpenter",
            "secretary",
            "secretary",//35
            "secretary",
            "pilot",
            "pilot",
            "pilot",
            "programmer",//40
            "programmer",
            "programmer",
            "professor",
            "professor",
            "professor",//45
            "bookkeeper",
            "bookkeeper",
            "bookkeeper",
            "sales manager",
            "sales manager",//50
            "sales manager",
            "sales manager",
            "sales manager",
            "sales manager",
            "programmer",//55
            "programmer",
            "programmer",
            "mechanic",
            "mechanic",
            "mechanic",//60
            "architect",
            "architect",
            "architect",
            "programmer",
            "programmer",//65
            "programmer",
            "student",
            "student",
            "student",
            "lawyer",//70
            "lawyer",
            "lawyer",
            "professor",
            "professor",
            "professor",//75
            "sales manager",
            "sales manager",
            "sales manager",
            "sales manager",
            "sales manager",//80
            "sales manager",
            "doctor",
            "doctor",
            "doctor",
            "lawyer",//85
            "lawyer",
            "lawyer",
            "teacher",
            "teacher",
            "teacher",//90
            "sales manager",
            "sales manager",
            "sales manager",
            "mechanic",
            "mechanic",//95
            "mechanic",
            "secretary",
            "secretary",
            "secretary",
            "student",//100
            "student",
            "student",
            "student",
            "student",
            "student",//105
            "professor",
            "professor",
            "professor",
            "mechanic",
            "mechanic",//110
            "mechanic",
            "doctor",
            "doctor",
            "doctor",
            "chemist",//115
            "chemist",
            "chemist",
            "architect",
            "architect",
            "architect",//120
            "student",
            "student",
            "student",
            "sales manager",
            "sales manager",//125
            "sales manager",
            "programmer",
            "programmer",
            "programmer",
            "professor",//130
            "professor",
            "professor",
            "student",
            "student",
            "student",//135
            "architect",
            "architect",
            "architect",
            "student",
            "student",//140
            "student",
            "doctor",
            "doctor",
            "doctor",
            "student",//145
            "student",
            "student",
            "welder",
            "welder",
            "welder",//150
            "programmer",
            "programmer",
            "programmer",
            "carpenter",
            "carpenter",//155
            "carpenter",
            "programmer",
            "programmer",
            "programmer",
            "bookkeeper",//160
            "bookkeeper",
            "bookkeeper",
            "architect",
            "architect",
            "architect",//165
            "contractor",
            "contractor",
            "contractor",
            "teacher",
            "teacher",//170
            "teacher",
            "secretary",
            "secretary",
            "secretary",
            "programmer",//175
            "programmer",
            "programmer",
            "programmer",
            "programmer",
            "programmer",//180
            "doctor",
            "doctor",
            "doctor",
            "contractor",
            "contractor",//185
            "contractor",
            "welder",
            "welder",
            "welder",
            "bookkeeper",//190
            "bookkeeper",
            "bookkeeper",
            "programmer",
            "programmer",
            "programmer",//195
            "pilot",
            "pilot",
            "pilot",
            "professor",
            "professor",//200
            "professor",
            "architect",
            "architect",
            "architect",
            "contractor",//205
            "contractor",
            "contractor",
            "programmer",
            "programmer",
            "programmer",//210
            "sales manager",
            "sales manager",
            "sales manager",
            "professor",
            "professor",//215
            "professor",
            "sales manager",
            "sales manager",
            "sales manager",
            "mechanic",//220
            "mechanic",
            "mechanic",
            "bookkeeper",
            "bookkeeper",
            "bookkeeper",//225
            "programmer",
            "programmer",
            "programmer",
            "architect",
            "architect",//230
            "architect",
            "chemist",
            "chemist",
            "chemist",
            "teacher",//235
            "teacher",
            "teacher",
            "bookkeeper",
            "bookkeeper",
            "bookkeeper",//240
            "sales manager",
            "sales manager",
            "sales manager",
            "professor",
            "professor",//245
            "professor",
            "doctor",
            "doctor",
            "doctor",
            "sales manager",//250
            "sales manager",
            "sales manager",
            "doctor",
            "doctor",
            "doctor",//255
            "programmer",
            "programmer",
            "programmer",
            "programmer",
            "programmer",//260
            "programmer",
            "sales manager",
            "sales manager",
            "sales manager",
            "carpenter",//265
            "carpenter",
            "carpenter",
            "carpenter",
            "carpenter",
            "carpenter",//270
            "mechanic",
            "mechanic",
            "mechanic",
            "architect",
            "architect",//275
            "architect",
            "engineer",
            "engineer",
            "engineer",
            "carpenter",//280
            "carpenter",
            "carpenter",
            "chemist",
            "chemist",
            "chemist",//285
            "secretary",
            "secretary",
            "secretary",
            "mechanic",
            "mechanic",//290
            "mechanic",
            "sales manager",
            "sales manager",
            "sales manager",
            "pilot",//295
            "pilot",
            "pilot",
            "architect",
            "architect",
            "architect",//300
            "carpenter",
            "carpenter",
            "carpenter",
            "pilot",
            "pilot",//305
            "pilot",
            "engineer",
            "engineer",
            "engineer",
            "chemist",//310
            "chemist",
            "chemist",
            "carpenter",
            "carpenter",
            "carpenter",//315
            "programmer",
            "programmer",
            "programmer",
            "chemist",
            "chemist",//320
            "chemist",
            "doctor",
            "doctor",
            "doctor",
            "contractor",//325
            "contractor",
            "contractor",
            "pilot",
            "pilot",
            "pilot",//330
            "carpenter",
            "carpenter",
            "carpenter",
            "mechanic",
            "mechanic",//335
            "mechanic",
            "engineer",
            "engineer",
            "engineer",
            "architect",//340
            "architect",
            "architect",
            "student",
            "student",
            "student",//345
            "engineer",
            "engineer",
            "engineer",
            "doctor",
            "doctor",//350
            "doctor",
            "student",
            "student",
            "student",
            "welder",//355
            "welder",
            "welder",
            "programmer",
            "programmer",
            "programmer",//360
            "welder",
            "welder",
            "welder",
            "secretary",
            "secretary",//365
            "secretary",
            "professor",
            "professor",
            "professor",
            "doctor",//370
            "doctor",
            "doctor",
            "mechanic",
            "mechanic",
            "mechanic",//375
            "mechanic",
            "mechanic",
            "mechanic",
            "bookkeeper",
            "bookkeeper",//380
            "bookkeeper",
            "lawyer",
            "lawyer",
            "lawyer",
            "student",//385
            "student",
            "student",
            "sales manager",
            "sales manager",
            "sales manager",//390
            "bookkeeper",
            "bookkeeper",
            "bookkeeper",
            "secretary",
            "secretary",//395
            "secretary",
            "lawyer",
            "lawyer",
            "lawyer",
            "programmer",//400
            "programmer",
            "programmer",
            "sales manager",
            "sales manager",
            "sales manager",//405
            "bookkeeper",
            "bookkeeper",
            "bookkeeper",
            "lawyer",
            "lawyer",//410
            "lawyer",
            "lawyer",
            "lawyer",
            "lawyer",
            "sales manager",//415
            "sales manager",
            "sales manager",
            "pilot",
            "pilot",
            "pilot",//420
            "secretary",
            "secretary",
            "secretary",
            "chemist",
            "chemist",//425
            "chemist",
            "doctor",
            "doctor",
            "doctor",
            "lawyer",//430
            "lawyer",
            "lawyer",
            "doctor",
            "doctor",
            "doctor",//435
            "doctor",
            "doctor",
            "doctor",
            "lawyer",
            "lawyer",//440
            "lawyer",
            "programmer",
            "programmer",
            "programmer",
            "contractor",//445
            "contractor",
            "contractor",
            "sales manager",
            "sales manager",
            "sales manager",//450
            "contractor",
            "contractor",
            "contractor",
            "engineer",
            "engineer",//455
            "engineer",
            "contractor",
            "contractor",
            "contractor",
            "lawyer",//460
            "lawyer",
            "lawyer",
            "engineer",
            "engineer",
            "engineer",//465
            "carpenter",
            "carpenter",
            "carpenter",
            "welder",
            "welder",//470
            "welder",
            "lawyer",
            "lawyer",
            "lawyer",
            "student",//475
            "student",
            "student",
            "welder",
            "welder",
            "welder",//480
            "architect",
            "architect",
            "architect",
            "contractor",
            "contractor",//485
            "contractor",
            "pilot",
            "pilot",
            "pilot",
            "secretary",//490
            "secretary",
            "secretary",
            "architect",
            "architect",
            "architect",//495
            "sales manager",
            "sales manager",
            "sales manager",
            "chemist",
            "chemist",//500
            "chemist",
            "architect",
            "architect",
            "architect",
            "teacher",//505
            "teacher",
            "teacher",
            "architect",
            "architect",
            "architect",//510
            "professor",
            "professor",
            "professor",
            "architect",
            "architect",//515
            "architect",
            "lawyer",
            "lawyer",
            "lawyer",
            "welder",//520
            "welder",
            "welder",
            "engineer",
            "engineer",
            "engineer",//525
            "carpenter",
            "carpenter",
            "carpenter",
            "carpenter",
            "carpenter",//530
            "carpenter",
            "professor",
            "professor",
            "professor",
            "contractor",//535
            "contractor",
            "contractor",
            "doctor",
            "doctor",
            "doctor",//540
            "mechanic",
            "mechanic",
            "mechanic",
            "welder",
            "welder",//545
            "welder",
            "sales manager",
            "sales manager",
            "sales manager",
            "programmer",//550
            "programmer",
            "programmer",
            "mechanic",
            "mechanic",
            "mechanic",//555
            "architect",
            "architect",
            "architect",
            "chemist",
            "chemist",//560
            "chemist",
            "mechanic",
            "mechanic",
            "mechanic",
            "programmer",//565
            "programmer",
            "programmer",
            "student",
            "student",
            "student",//570
            "doctor",
            "doctor",
            "doctor",
            "architect",
            "architect",//575
            "architect",
            "professor",
            "professor",
            "professor",
            "chemist",//580
            "chemist",
            "chemist",
            "chemist",
            "chemist",
            "chemist",//585
            "secretary",
            "secretary",
            "secretary",
            "architect",
            "architect",//590
            "architect",
            "professor",
            "professor",
            "professor",
            "programmer",//595
            "programmer",
            "programmer",
            "student",
            "student",
            "student",//600
            "sales manager",
            "sales manager",
            "sales manager",
            "engineer",
            "engineer",//605
            "engineer",
            "carpenter",
            "carpenter",
            "carpenter",
            "engineer",//610
            "engineer",
            "engineer",
            "professor",
            "professor",
            "professor",//615
            "professor",
            "professor",
            "professor",
            "bookkeeper",
            "bookkeeper",//620
            "bookkeeper",
            "programmer",
            "programmer",
            "programmer",
            "welder",//625
            "welder",
            "welder",
            "student",
            "student",
            "student",//630
            "bookkeeper",
            "bookkeeper",
            "bookkeeper",
            "student",
            "student",//635
            "student",
            "mechanic",
            "mechanic",
            "mechanic",
            "contractor",//640
            "contractor",
            "contractor",
            "professor",
            "professor",
            "professor",//645
            "doctor",
            "doctor",
            "doctor",
            "chemist",
            "chemist",//650
            "chemist",
            "sales manager",
            "sales manager",
            "sales manager",
            "welder",//655
            "welder",
            "welder",
            "contractor",
            "contractor",
            "contractor",//660
            "mechanic",
            "mechanic",
            "mechanic",
            "student",
            "student",//665
            "student",
            "teacher",
            "teacher",
            "teacher",
            "professor",//670
            "professor",
            "professor",
            "bookkeeper",
            "bookkeeper",
            "bookkeeper",//675
            "lawyer",
            "lawyer",
            "lawyer",
            "architect",
            "architect",//680
            "architect",
            "contractor",
            "contractor",
            "contractor",
            "lawyer",//685
            "lawyer",
            "lawyer",
            "contractor",
            "contractor",
            "contractor",//690
            "welder",
            "welder",
            "welder",
            "student",
            "student",//695
            "student",
            "engineer",
            "engineer",
            "engineer",
            "engineer",//700
            "engineer",
            "engineer",
            "welder",
            "welder",
            "welder",//705
            "lawyer",
            "lawyer",
            "lawyer",
            "teacher",
            "teacher",//710
            "teacher",
            "doctor",
            "doctor",
            "doctor",
            "sales manager",//715
            "sales manager",
            "sales manager",
            "chemist",
            "chemist",
            "chemist",//720
            "lawyer",
            "lawyer",
            "lawyer",
            "pilot",
            "pilot",//725
            "pilot",
            "programmer",
            "programmer",
            "programmer",
            "chemist",//730
            "chemist",
            "chemist",
            "bookkeeper",
            "bookkeeper",
            "bookkeeper",//735
            "student",
            "student",
            "student",
            "programmer",
            "programmer",//740
            "programmer",
            "chemist",
            "chemist",
            "chemist",
            "lawyer",//745
            "lawyer",
            "lawyer",
            "teacher",
            "teacher",
            "teacher",//750
            "contractor",
            "contractor",
            "contractor",
            "mechanic",
            "mechanic",//755
            "mechanic",
            "professor",
            "professor",
            "professor",
            "teacher",//760
            "teacher",
            "teacher",
            "contractor",
            "contractor",
            "contractor",//765
            "professor",
            "professor",
            "professor",
            "professor",
            "professor",//770
            "professor",
            "welder",
            "welder",
            "welder",
            "contractor",//775
            "contractor",
            "contractor",
            "doctor",
            "doctor",
            "doctor",//780
            "engineer",
            "engineer",
            "engineer",
            "sales manager",
            "sales manager",//785
            "sales manager",
            "student",
            "student",
            "student",
            "pilot",//790
            "pilot",
            "pilot",
            "secretary",
            "secretary",
            "secretary",//795
            "welder",
            "welder",
            "welder",
            "engineer",
            "engineer",//800
            "engineer",
            "lawyer",
            "lawyer",
            "lawyer",
            "mechanic",//805
            "mechanic",
            "mechanic",
            "welder",
            "welder",
            "welder",//810
            "secretary",
            "secretary",
            "secretary",
            "welder",
            "welder",//815
            "welder",
            "programmer",
            "programmer",
            "programmer",
            "teacher",//820
            "teacher",
            "teacher",
            "professor",
            "professor",
            "professor",//825
            "engineer",
            "engineer",
            "engineer",
            "student",
            "student",//830
            "student",
            "architect",
            "architect",
            "architect",
            "welder",//835
            "welder",
            "welder",
            "programmer",
            "programmer",
            "programmer",//840
            "welder",
            "welder",
            "welder",
            "student",
            "student",//845
            "student",
            "programmer",
            "programmer",
            "programmer",
            "teacher",//850
            "teacher",
            "teacher",
            "programmer",
            "programmer",
            "programmer",//855
            "professor",
            "professor",
            "professor",
            "secretary",
            "secretary",//860
            "secretary",
            "professor",
            "professor",
            "professor",
            "carpenter",//865
            "carpenter",
            "carpenter",
            "doctor",
            "doctor",
            "doctor",//870
            "pilot",
            "pilot",
            "pilot",
            "teacher",
            "teacher",//875
            "teacher",
            "engineer",
            "engineer",
            "engineer",
            "secretary",//880
            "secretary",
            "secretary",
            "student",
            "student",
            "student",//885
            "contractor",
            "contractor",
            "contractor",
            "chemist",
            "chemist",//890
            "chemist",
            "carpenter",
            "carpenter",
            "carpenter",
            "engineer",//895
            "engineer",
            "engineer",
            "chemist",
            "chemist",
            "chemist"//900
        });
    }
}
