using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QSO_Trainer.Lister
{
public    class RxNames
    {
        public static List<string> RxName = new List<string>(new string[] {
            "mickey",
            "mickey",
            "mickey",
            "edward",
            "edward",//5
            "edward",
            "ed",
            "ed",
            "ed",
            "alex",//10
            "alex",
            "alex",
            "liza",
            "liza",
            "liza",//15
            "james",
            "james",
            "james",
            "ann",
            "ann",//20
            "ann",
            "robert",
            "robert",
            "robert",
            "tom",//25
            "tom",
            "tom",
            "nick",
            "nick",
            "nick",//30
            "catherine",
            "catherine",
            "catherine",
            "anne",
            "anne",//35
            "anne",
            "edward",
            "edward",
            "edward",
            "anne",//40
            "anne",
            "anne",
            "beth",
            "beth",
            "beth",//45
            "rachel",
            "rachel",
            "rachel",
            "thom",
            "thom",//50
            "thom",
            "josh",
            "josh",
            "josh",
            "joseph",//55
            "joseph",
            "joseph",
            "william",
            "william",
            "william",//60
            "matthew",
            "matthew",
            "matthew",
            "ann",
            "ann",//65
            "ann",
            "rachel",
            "rachel",
            "rachel",
            "matthew",//70
            "matthew",
            "matthew",
            "josh",
            "josh",
            "josh",//75
            "robert",
            "robert",
            "robert",
            "bill",
            "bill",//80
            "bill",
            "johnny",
            "johnny",
            "johnny",
            "micael",//85
            "michael",
            "michael",
            "jim",
            "jim",
            "jim",//90
            "elizabeth",
            "elizabeth",
            "elizabeth",
            "michael",
            "michael",//95
            "michael",
            "anne",
            "anne",
            "anne",
            "grace",//100
            "grace",
            "grace",
            "alex",
            "alex",
            "alex",//105
            "tom",
            "tom",
            "tom",
            "james",
            "james",//110
            "james",
            "jim",
            "jim",
            "jim",
            "hank",//115
            "hank",
            "hank",
            "david",
            "david",
            "david",//120
            "rachel",
            "rachel",
            "rachel",
            "lucy",
            "lucy",//125
            "lucy",
            "alex",
            "alex",
            "alex",
            "becky",//130
            "becky",
            "becky",
            "samuel",
            "samuel",
            "samuel",//135
            "vicky",
            "vicky",
            "vicky",
            "vickie",
            "vickie",//140
            "vickie",
            "vicky",
            "vicky",
            "vicky",
            "andy",//145
            "andy",
            "andy",
            "grace",
            "grace",
            "grace",//150
            "ed",
            "ed",
            "ed",
            "alice",
            "alice",//155
            "alice",
            "alice",
            "alice",
            "alice",
            "sam",//160
            "sam",
            "sam",
            "claire",
            "claire",
            "claire",//165
            "kate",
            "kate",
            "kate",
            "joshua",
            "joshua",//170
            "joshua",
            "thomas",
            "thomas",
            "thomas",
            "jack",//175
            "jack",
            "jack",
            "patrick",
            "patrick",
            "patrick",//180
            "jane",
            "jane",
            "jane",
            "josh",
            "josh",//185
            "josh",
            "jimmy",
            "jimmy",
            "jimmy",
            "john",//190
            "john",
            "john",
            "alice",
            "alice",
            "alice",//195
            "johnny",
            "johnny",
            "johnny",
            "kathryn",
            "kathryn",//200
            "kathryn",
            "tom",
            "tom",
            "tom",
            "jim",//205
            "jim",
            "jim",
            "elizabeth",
            "elizabeth",
            "elizabeth",//210
            "anne",
            "anne",
            "anne",
            "joseph",
            "joseph",//215
            "joseph",
            "bill",
            "bill",
            "bill",
            "vicky",//220
            "vicky",
            "vicky",
            "bill",
            "bill",
            "bill",//225
            "anne",
            "anne",
            "anne",
            "kate",
            "kate",//230
            "kate",
            "anne",
            "anne",
            "anne",
            "alice",//235
            "alice",
            "alice",
            "lucy",
            "lucy",
            "lucy",//240
            "kate",
            "kate",
            "kate",
            "bill",
            "bill",//245
            "bill",
            "edward",
            "edward",
            "edward",
            "dan",//250
            "dan",
            "dan",
            "thomas",
            "thomas",
            "thomas",//255
            "bob",
            "bob",
            "bob",
            "joseph",
            "joseph",//260
            "joseph",
            "alice",
            "alice",
            "alice",
            "mike",//265
            "mike",
            "mike",
            "matt",
            "matt",
            "matt",//270
            "simon",
            "simon",
            "simon",
            "joseph",
            "joseph",//275
            "joseph",
            "james",
            "james",
            "james",
            "alice",//280
            "alice",
            "alice",
            "edward",
            "edward",
            "edward",//285
            "james",
            "james",
            "james",
            "joe",
            "joe",//290
            "joe",
            "johnny",
            "johnny",
            "johnny",
            "billy",//295
            "billy",
            "billy",
            "johnny",
            "johnny",
            "johnny",//300
            "liz",
            "liz",
            "liz",
            "josh",
            "josh",//305
            "josh",
            "jack",
            "jack",
            "jack",
            "cathy",//310
            "cathy",
            "cathy",
            "vicky",
            "vicky",
            "vicky",//315
            "bob",
            "bob",
            "bob",
            "william",
            "william",//320
            "william",
            "joshua",
            "joshua",
            "joshua",
            "john",//325
            "john",
            "john",
            "cathy",
            "cathy",
            "cathy",//330
            "mickey",
            "mickey",
            "mickey",
            "daniel",
            "daniel",//335
            "daniel",
            "cathy",
            "cathy",
            "cathy",
            "edward",//340
            "edward",
            "edward",
            "liz",
            "liz",
            "liz",//345
            "jack",
            "jack",
            "jack",
            "claire",
            "claire",//350
            "claire",
            "joshua",
            "joshua",
            "joshua",
            "edward",//355
            "edward",
            "edward",
            "patrick",
            "patrick",
            "patrick",//360
            "joshua",
            "joshua",
            "joshua",
            "kathryn",
            "kathryn",//365
            "kathryn",
            "alex",
            "alex",
            "alex",
            "sam",//370
            "sam",
            "sam",
            "claire",
            "claire",
            "claire",//375
            "liza",
            "liza",
            "liza",
            "grace",
            "grace",//380
            "grace",
            "beth",
            "beth",
            "beth",
            "jane",//385
            "jane",
            "jane",
            "danny",
            "danny",
            "danny",//390
            "rachel",
            "rachel",
            "rachel",
            "beth",
            "beth",//395
            "beth",
            "grace",
            "grace",
            "grace",
            "laura",//400
            "laura",
            "laura",
            "bill",
            "bill",
            "bill",//405
            "vickie",
            "vickie",
            "vickie",
            "emma",
            "emma",//410
            "emma",
            "rachel",
            "rachel",
            "rachel",
            "liz",//415
            "liz",
            "liz",
            "julie",
            "julie",
            "julie",//420
            "tom",
            "tom",
            "tom",
            "ed",
            "ed",//425
            "ed",
            "liz",
            "liz",
            "liz",
            "emma",//430
            "emma",
            "emma",
            "kate",
            "kate",
            "kate",//435
            "nicholas",
            "nicholas",
            "nicholas",
            "grace",
            "grace",//440
            "grace",
            "vicky",
            "vicky",
            "vicky",
            "alice",//445
            "alice",
            "alice",
            "alice",
            "alice",
            "alice",//450
            "grace",
            "grace",
            "grace",
            "matthew",
            "matthew",//455
            "matthew",
            "catherine",
            "catherine",
            "catherine",
            "sarah",//460
            "sarah",
            "sarah",
            "hank",
            "hank",
            "hank",//465
            "laura",
            "laura",
            "laura",
            "nicholas",
            "nicholas",//470
            "nicholas",
            "liz",
            "liz",
            "liz",
            "john",//475
            "john",
            "john",
            "alice",
            "alice",
            "alice",//480
            "sarah",
            "sarah",
            "sarah",
            "rachel",
            "rachel",//485
            "rachel",
            "hank",
            "hank",
            "hank",
            "patrick",//490
            "patrick",
            "patrick",
            "tom",
            "tom",
            "tom",//495
            "thom",
            "thom",
            "thom",
            "josh",
            "josh",//500
            "josh",
            "anne",
            "anne",
            "anne",
            "emma",//505
            "emma",
            "emma",
            "becky",
            "becky",
            "becky",//510
            "kathy",
            "kathy",
            "kathy",
            "grace",
            "grace",//515
            "grace",
            "bobby",
            "bobby",
            "bobby",
            "matt",//520
            "matt",
            "matt",
            "claire",
            "claire",
            "claire",//525
            "johnny",
            "johnny",
            "johnny",
            "matthew",
            "matthew",//530
            "matthew",
            "thomas",
            "thomas",
            "thomas",
            "thomas",//535
            "thomas",
            "thomas",
            "james",
            "james",
            "james",//540
            "danny",
            "danny",
            "danny",
            "grace",
            "grace",//545
            "grace",
            "william",
            "william",
            "william",
            "eddie",//550
            "eddie",
            "eddie",
            "ed",
            "ed",
            "ed",//555
            "sarah",
            "sarah",
            "sarah",
            "sophie",
            "sophie",//560
            "sophie",
            "beth",
            "beth",
            "beth",
            "becky",//565
            "becky",
            "becky",
            "robert",
            "robert",
            "robert",//570
            "vicky",
            "vicky",
            "vicky",
            "jimmy",
            "jimmy",//575
            "jimmy",
            "patrick",
            "patrick",
            "patrick",
            "michael",//580
            "michael",
            "michael",
            "ed",
            "ed",
            "ed",//585
            "billy",
            "billy",
            "billy",
            "jim",
            "jim",//590
            "jim",
            "michael",
            "michael",
            "michael",
            "andy",//595
            "andy",
            "andy",
            "samuel",
            "samuel",
            "samuel",//600
            "pat",
            "pat",
            "pat",
            "rachel",
            "rachel",//605
            "rachel",
            "catherine",
            "catherine",
            "catherine",
            "henry",//610
            "henry",
            "henry",
            "kathy",
            "kathy",
            "kathy",//615
            "laura",
            "laura",
            "laura",
            "sam",
            "sam",//620
            "sam",
            "sarah",
            "sarah",
            "sarah",
            "michael",//625
            "michael",
            "michael",
            "thom",
            "thom",
            "thom",//630
            "dan",
            "dan",
            "dan",
            "dave",
            "dave",//635
            "dave",
            "catherine",
            "catherine",
            "catherine",
            "kathryn",//640
            "kathryn",
            "kathryn",
            "alice",
            "alice",
            "alice",//645
            "henry",
            "henry",
            "henry",
            "daniel",
            "daniel",//650
            "daniel",
            "samuel",
            "samuel",
            "samuel",
            "thom",//655
            "thom",
            "thom",
            "edward",
            "edward",
            "edward",//600
            "henry",
            "henry",
            "henry",
            "joshua",
            "joshua",//665
            "joshua",
            "tom",
            "tom",
            "tom",
            "mickey",//670
            "mickey",
            "mickey",
            "matt",
            "matt",
            "matt",//675
            "pat",
            "pat",
            "pat",
            "michael",
            "michael",//680
            "michael",
            "john",
            "john",
            "john",
            "patrick",//685
            "patrick",
            "patrick",
            "dave",
            "dave",
            "dave",//690
            "william",
            "william",
            "william",
            "kathryn",
            "kathryn",//695
            "kathryn",
            "alice",
            "alice",
            "alice",
            "elizabeth",//700
            "elizabeth",
            "elizabeth",
            "thomas",
            "thomas",
            "thomas",//705
            "bobby",
            "bobby",
            "bobby",
            "nick",
            "nick",//710
            "nick",
            "nick",
            "nick",
            "nick",
            "mickey",//715
            "mickey",
            "mickey",
            "bobby",
            "bobby",
            "bobby",//720
            "kathy",
            "kathy",
            "kathy",
            "liz",
            "liz",//725
            "liz",
            "edward",
            "edward",
            "edward",
            "edward",//730
            "edward",
            "edward",
            "rachel",
            "rachel",
            "rachel",//735
            "nick",
            "nick",
            "nick",
            "joseph",
            "joseph",//740
            "joseph",
            "ed",
            "ed",
            "ed",
            "julie",//745
            "julie",
            "julie",
            "becky",
            "becky",
            "becky",//750
            "cathy",
            "cathy",
            "cathy",
            "lucy",
            "lucy",//755
            "lucy",
            "sarah",
            "sarah",
            "sarah",
            "eddie",//760
            "eddie",
            "eddie",
            "joe",
            "joe",
            "joe",//765
            "grace",
            "grace",
            "grace",
            "rachel",
            "rachel",//770
            "rachel",
            "liza",
            "liza",
            "liza",
            "bobby",//775
            "bobby",
            "bobby",
            "bob",
            "bob",
            "bob",//780
            "jimmy",
            "jimmy",
            "jimmy",
            "andy",
            "andy",//785
            "andy",
            "andy",
            "andy",
            "andy",
            "sophie",//790
            "sophie",
            "sophie",
            "bob",
            "bob",
            "bob",//795
            "mickey",
            "mickey",
            "mickey",
            "sam",
            "sam",//800
            "sam",
            "eddie",
            "eddie",
            "eddie",
            "william",//805
            "william",
            "william",
            "kathy",
            "kathy",
            "kathy",//810
            "jack",
            "jack",
            "jack",
            "grace",
            "grace",//815
            "grace",
            "joseph",
            "joseph",
            "joseph",
            "cathy",//820
            "cathy",
            "cathy",
            "mike",
            "mike",
            "mike",//825
            "sarah",
            "sarah",
            "sarah",
            "samuel",
            "samuel",//830
            "samuel",
            "johnny",
            "johnny",
            "johnny",
            "simon",//835
            "simon",
            "simon",
            "tom",
            "tom",
            "tom",//840
            "sam",
            "sam",
            "sam",
            "danny",
            "danny",//845
            "danny",
            "joseph",
            "joseph",
            "joseph",
            "bob",//850
            "bob",
            "bob",
            "sophie",
            "sophie",
            "sophie",//855
            "robert",
            "robert",
            "robert",
            "joe",
            "joe",//860
            "joe",
            "josh",
            "josh",
            "josh",
            "david",//865
            "david",
            "david",
            "william",
            "william",
            "william",//870
            "sophie",
            "sophie",
            "sophie",
            "mickey",
            "mickey",//875
            "mickey",
            "pat",
            "pat",
            "pat",
            "matt",//880
            "matt",
            "matt",
            "bob",
            "bob",
            "bob",//885
            "henry",
            "henry",
            "henry",
            "bill",
            "bill",//890
            "bill",
            "johnny",
            "johnny",
            "johnny",
            "robert",//895
            "robert",
            "robert",
            "kathryn",
            "kathryn",
            "kathryn"//900
        });
    }
}
