using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QSO_Trainer.Lister
{
public  class TxCalls
    {
        public static List<string> TxCall = new List<string>(new string[] {
            "q4xxj/0",
            "q4xxj/0",
            "q4xxj",
            "q8t/7",
            "q8t/7",//5
            "q8t",
            "q0tsl/5",
            "q0tsl/5",
            "q0tsl",
            "q3zrp/7",//10
            "q3zrp/7",
            "q3zrp",
            "q6yok/3",
            "q6yok/3",
            "q6yok",//15
            "q4zxm/0",
            "q4zxm/0",
            "q4zxm",
            "q5xpu/2",
            "q5xpu/2",//20
            "q5xpu",
            "q5xyz/3",
            "q5xyz/3",
            "q5xyz",
            "q3pvx/4",//25
            "q3pvx/4",
            "q3pvx",
            "q4yjx/9",
            "q4yjx/9",
            "q4yjx",//30
            "q2vl/7",
            "q2vl/7",
            "q2vl",
            "q4pqp/6",
            "q4pqp/6",//35
            "q4pqp",
            "q9zqc/5",
            "q9zqc/5",
            "q9zqc",
            "q5xzj/6",//40
            "q5xzj/6",
            "q5xzj",
            "q3xv/9",
            "q3xv/9",
            "q3xv",//45
            "q3yqr/1",
            "q3yqr/1",
            "q3yqr",
            "q0xm/2",
            "q0xm/2",//50
            "q0xm",
            "q1qq/1",
            "q1qq/1",
            "q1qq",
            "q5mob/9",//55
            "q5mob/9",
            "q5mob",
            "q1yyy/1",
            "q1yyy/1",
            "q1yyy",//60
            "q4jzk/4",
            "q4jzk/4",
            "q4jzk",
            "q0yiz/3",
            "q0yiz/3",//65
            "q0yiz",
            "q2jz/0",
            "q2jz/0",
            "q2jz",
            "q1xjx/8",//70
            "q1xjx/8",
            "q1xjx",
            "q1qae/5",
            "q1qae/5",
            "q1qae",//75
            "q3vq/9",
            "q3vq/9",
            "q3vq",
            "q4xqx/7",
            "q4xqx/7",//80
            "q4xqx",
            "q0qzq/9",
            "q0qzq/9",
            "q0qzq",
            "q6xp/8",//85
            "q6xp/8",
            "q6xp",
            "q7yys/2",
            "q7yys/2",
            "q7yys",//90
            "q7uv/9",
            "q7uv/9",
            "q7uv",
            "q1zuw/7",
            "q1zuw/7",//95
            "q1zuw",
            "q0qvm/4",
            "q0qvm/4",
            "q0qvm",
            "q8xyq/0",//100
            "q8xyq/0",
            "q8xyq",
            "q7q3z/7",
            "q7q3z/7",
            "q7q3z",//105
            "q9qse/5",
            "q9qse/5",
            "q9qse",
            "q5xzx/7",
            "q5xzx/7",//110
            "q5xzx",
            "q0guy/9",
            "q0guy/9",
            "q0guy",
            "q2q4x/8",//115
            "q2q4x/8",
            "q2q4x",
            "q9zi/7",
            "q9zi/7",
            "q9zi",//120
            "q5vxx/8",
            "q5vxx/8",
            "q5vxx",
            "q0yux/5",
            "q0yux/5",//125
            "q0yux",
            "q9jqz/3",
            "q9jqz/3",
            "q9jqz",
            "q2xpa/9",//130
            "q2xpa/9",
            "q2xpa",
            "q0qvr/3",
            "q0qvr/3",
            "q0qvr",//135
            "q5pw/6",
            "q5pw/6",
            "q5pw",
            "q8yxz/7",
            "q8yxz/7",//140
            "q8yxz",
            "q1by/8",
            "q1by/8",
            "q1by",
            "q5vyy/6",//145
            "q5vyy/6",
            "q5vyy",
            "q1q4x/6",
            "q1q4x/6",
            "q1q4x",//150
            "q2yq1/6",
            "q2yq1/6",
            "q2yq1",
            "q0qxx/1",
            "q0qxx/1",//155
            "q0qxx",
            "q7py/1",
            "q7py/1",
            "q7py",
            "q1uxx/1",//160
            "q1uxx/1",
            "q1uxx",
            "q8qw/7",
            "q8qw/7",
            "q8qw",//165
            "q9yqn/4",
            "q9yqn/4",
            "q9yqn",
            "q4uq8/2",
            "q4uq8/2",//170
            "q4uq8",
            "q4yu/4",
            "q4yu/4",
            "q4yu",
            "q2j/5",//175
            "q2j/5",
            "q2j",
            "q7zn/8",
            "q7zn/8",
            "q7zn",//180
            "q0q4/0",
            "q0q4/0",
            "q0q4",
            "q6jlj/4",
            "q6jlj/4",//185
            "q6jlj",
            "q3zc/0",
            "q3zc/0",
            "q3zc",
            "q7qxy/5",//190
            "q7qxy/5",
            "q7qxy",
            "q7rq4/2",
            "q7rq4/2",
            "q7rq4",//195
            "q1ygv/8",
            "q1ygv/8",
            "q1ygv",
            "q2q1p/2",
            "q2q1p/2",//200
            "q2q1p",
            "q3yz/7",
            "q3yz/7",
            "q3yz",
            "q1xxu/1",//205
            "q1xxu/1",
            "q1xxu",
            "q5vzq/7",
            "q5vzq/7",
            "q5vzq",//210
            "q3qcw/4",
            "q3qcw/4",
            "q3qcw",
            "q6qpp/4",
            "q6qpp/4",//215
            "q6qpp",
            "q8zbz/6",
            "q8zbz/6",
            "q8zbz",
            "q6vxj/1",//220
            "q6vxj/1",
            "q6vxj",
            "q8ysh/1",
            "q8ysh/1",
            "q8ysh",//225
            "q4q4x/1",
            "q4q4x/1",
            "q4q4x",
            "q4yjz/8",
            "q4yjz/8",//230
            "q4yjz",
            "q4qyq/0",
            "q4qyq/0",
            "q4qyq",
            "q1yyx/3",//235
            "q1yyx/3",
            "q1yyx",
            "q8q1/0",
            "q8q1/0",
            "q8q1",//240
            "q0z/1",
            "q0z/1",
            "q0z",
            "q4xxb/4",
            "q4xxb/4",//245
            "q4xxb",
            "q1wro/5",
            "q1wro/5",
            "q1wro",
            "q3vtl/3",//250
            "q3vtl/3",
            "q3vtl",
            "q5q9x/0",
            "q5q9x/0",
            "q5q9x",//255
            "q2zz/6",
            "q2zz/6",
            "q2zz",
            "q6qpv/2",
            "q6qpv/2",//260
            "q6qpv",
            "q9oyg/3",
            "q9oyg/3",
            "q9oyg",
            "q5jjj/1",//265
            "q5jjj/1",
            "q5jjj",
            "q1txq/8",
            "q1txq/8",
            "q1txq",//270
            "q0yf/5",
            "q0yf/5",
            "q0yf",
            "q0xq2/4",
            "q0xq2/4",//275
            "q0xq2",
            "q8qqz/2",
            "q8qqz/2",
            "q8qqz",
            "q9xtx/6",//280
            "q9xtx/6",
            "q9xtx",
            "q2q3/4",
            "q2q3/4",
            "q2q3",//285
            "q7xg/6",
            "q7xg/6",
            "q7xg",
            "q8q4y/7",
            "q8q4y/7",//290
            "q8q4y",
            "q2qyq/8",
            "q2qyq/8",
            "q2qyq",
            "q0zxc/6",//295
            "q0zxc/6",
            "q0zxc",
            "q6xbq/6",
            "q6xbq/6",
            "q6xbq",//300
            "q6qus/6",
            "q6qus/6",
            "q6qus",
            "q9yux/8",
            "q9yux/8",//305
            "q9yux",
            "q2vqy3",
            "q2vqy/3",
            "q2vqy",
            "q2xu/7",//310
            "q2xu/7",
            "q2xu",
            "q7yr/3",
            "q7yr/3",
            "q7yr",//315
            "q5q1y/1",
            "q5q1y/1",
            "q5q1y",
            "q6qyz/7",
            "q6qyz/7",//320
            "q6qyz",
            "q0jyz/8",
            "q0jyz/8",
            "q0jyz",
            "q1zyg/4",//325
            "q1zyg/4",
            "q1zyg",
            "q6zz/9",
            "q6zz/9",
            "q6zz",//330
            "q4sx/8",
            "q4sx/8",
            "q4sx",
            "q5jkr/4",
            "q5jkr/4",//335
            "q5jkr",
            "q6jq5/2",
            "q6jq5/2",
            "q6jq5",
            "q1jy/8",//340
            "q1jy/8",
            "q1jy",
            "q6q8j/5",
            "q6q8j/5",
            "q6q8j",//345
            "q9zx/2",
            "q9zx/2",
            "q9zx",
            "q0q92/6",
            "q0q92/6",//350
            "q0q92",
            "q8ryx/2",
            "q8ryx/2",
            "q8ryx",
            "q6spw/7",//355
            "q6spw/7",
            "q6spw",
            "q1oyp/8",
            "q1oyp/8",
            "q1oyp",//360
            "q3jqw/3",
            "q3jqw/3",
            "q3jqw",
            "q9mzj/0",
            "q9mzj/0",//365
            "q9mzj",
            "q9uy/3",
            "q9uy/3",
            "q9uy",
            "q2xxy/3",//370
            "q2xxy/3",
            "q2xxy",
            "q3xzs/1",
            "q3xzs/1",
            "q3xzs",//375
            "q8qaw/5",
            "q8qaw/5",
            "q8qaw",
            "q2xj/8",
            "q2xj/8",//380
            "q2xj",
            "q3ppu/5",
            "q3ppu/5",
            "q3ppu",
            "q9vex/2",//385
            "q9vex/2",
            "q9vex",
            "q8z/2",
            "q8z/2",
            "q8z",//390
            "q4zx/9",
            "q4zx/9",
            "q4zx",
            "q4yz/2",
            "q4yz/2",//395
            "q4yz",
            "q6zp/8",
            "q6zp/8",
            "q6zp",
            "q3jcq/5",//400
            "q3jcq/5",
            "q3jcq",
            "q3qzu/7",
            "q3qzu/7",
            "q3qzu",//405
            "q2yxj/8",
            "q2yxj/8",
            "q2yxj",
            "q9tyu/6",
            "q9tyu/6",//410
            "q9tyu",
            "q5jo/6",
            "q5jo/6",
            "q5jo",
            "q9bxq/9",//415
            "q9bxq/9",
            "q9bxq",
            "q5qrj/5",
            "q5qrj/5",
            "q5qrj",//420
            "q5qtp/8",
            "q5qtp/8",
            "q5qtp",
            "q5xu/2",
            "q5xu/2",//425
            "q5xu",
            "q0pqp/2",
            "q0pqp/2",
            "q0pqp",
            "q5yy/1",//430
            "q5yy/1",
            "q5yy",
            "q9ou/8",
            "q9ou/8",
            "q9ou",//435
            "q0zgj/1",
            "q0zgj/1",
            "q0zgj",
            "q0dm/6",
            "q0dm/6",//440
            "q0dm",
            "q1x/1",
            "q1x/1",
            "q1x",
            "q7uzx/7",//445
            "q7uzx/7",
            "q7uzx",
            "q8lz/1",
            "q8lz/1",
            "q8lz",//450
            "q1jzz/1",
            "q1jzz/1",
            "q1jzz",
            "q3qry/0",
            "q3qry/0",//455
            "q3qry",
            "q0q5w/2",
            "q0q5w/2",
            "q0q5w",
            "q8rjx/3",//460
            "q8rjx/3",
            "q8rjx",
            "q8qzu/4",
            "q8qzu/4",
            "q8qzu",//465
            "q4vpz/3",
            "q4vpz/3",
            "q4vpz",
            "q9dyy/9",
            "q9dyy/9",//470
            "q9dyy",
            "q4yjr/2",
            "q4yjr/2",
            "q4yjr",
            "q7qqg/3",//475
            "q7qqg/3",
            "q7qqg",
            "q2ccj/9",
            "q2ccj/9",
            "q2ccj",//480
            "q2qyy/5",
            "q2qyy/5",
            "q2qyy",
            "q4jyw/0",
            "q4jyw/0",//485
            "q4jyw",
            "q5zzz/1",
            "q5zzz/1",
            "q5zzz",
            "q4uzk/5",//490
            "q4uzk/5",
            "q4uzk",
            "q7oq3/2",
            "q7oq3/2",
            "q7oq3",//495
            "q7zw/2",
            "q7zw/2",
            "q7zw",
            "q5yqk/9",
            "q5yqk/9",//500
            "q5yqk",
            "q7zp/9",
            "q7zp/9",
            "q7zp",
            "q5zqz/1",//505
            "q5zqz/1",
            "q5zqz",
            "q9zp/3",
            "q9zp/3",
            "q9zp",//510
            "q3yu/4",
            "q3yu/4",
            "q3yu",
            "q5qyz/1",
            "q5qyz/1",//515
            "q5qyz",
            "ql4qd/2",
            "ql4qd/2",
            "ql4qd",
            "q6fpx/8",//520
            "q6fpx/8",
            "q6fpx",
            "q4uuy/6",
            "q4uuy/6",
            "q4uuy",//525
            "q8yx/2",
            "q8yx/2",
            "q8yx",
            "q4cxp/0",
            "q4cxp/0",//530
            "q4cxp",
            "q8qy/9",
            "q8qy/9",
            "q8qy",
            "q5zjq/9",//535
            "q5zjq/9",
            "q5zjq",
            "q4qiy/5",
            "q4qiy/5",
            "q4qiy",//540
            "q5qzq/4",
            "q5qzq/4",
            "q5qzq",
            "q5yy/3",
            "q5yy/3",//545
            "q5yy",
            "q5zry/8",
            "q5zry/8",
            "q5zry",
            "qs2xk/1",//550
            "qs2xk/1",
            "qs2xk",
            "q2zxf/4",
            "q2zxf/4",
            "q2zxf",//555
            "q4urw/3",
            "q4urw/3",
            "q4urw",
            "q2uzj/2",
            "q2uzj/2",//560
            "q2uzj",
            "q6zzx/6",
            "q6zzx/6",
            "q6zzx",
            "q1iw/7",//565
            "q1iw/7",
            "q1iw",
            "q0yy/3",
            "q0yy/3",
            "q0yy",//570
            "q2q5f/7",
            "q2q5f/7",
            "q2q5f",
            "q6ypq/6",
            "q6ypq/6",//575
            "q6ypq",
            "q7qjx/7",
            "q7qjx/7",
            "q7qjx",
            "q3qvb/4",//580
            "q3qvb/4",
            "q3qvb",
            "q2yud/8",
            "q2yud/8",
            "q2yud",//585
            "q9yzn/9",
            "q9yzn/9",
            "q9yzn",
            "q0bpx/4",
            "q0bpx/4",//590
            "q0bpx",
            "q1yzw/4",
            "q1yzw/4",
            "q1yzw",
            "q0jq/3",//595
            "q0jq/3",
            "q0jq",
            "q2q4/2",
            "q2q4/2",
            "q2q4",//600
            "q9sv/0",
            "q9sv/0",
            "q9sv",
            "q8qvz/2",
            "q8qvz/2",//605
            "q8qvz",
            "q7jym/4",
            "q7jym/4",
            "q7jym",
            "q5zus/9",//610
            "q5zus/9",
            "q5zus",
            "q9zep/1",
            "q9zep/1",
            "q9zep",//615
            "q5px/1",
            "q5px/1",
            "q5px",
            "q9ljd/0",
            "q9ljd/0",//620
            "q9ljd",
            "q2ylq/5",
            "q2ylq/5",
            "q2ylq",
            "q8zyz/4",//625
            "q8zyz/4",
            "q8zyz",
            "q4pw/0",
            "q4pw/0",
            "q4pw",//630
            "q7x/7",
            "q7x/7",
            "q7x",
            "q21me/7",
            "q21me/7",//635
            "q21me",
            "q2zzz/8",
            "q2zzz/8",
            "q2zzz",
            "q6xjz/2",//640
            "q6xjz/2",
            "q6xjz",
            "q0yq2/0",
            "q0yq2/0",
            "q0yq2",//645
            "q1zqw/4",
            "q1zqw/4",
            "q1zqw",
            "q3q3u/4",
            "q3q3u/4",//650
            "q3q3u",
            "q7pk/1",
            "q7pk/1",
            "q7pk",
            "q2q4x/5",//655
            "q2q4x/5",
            "q2q4x",
            "q0juu/7",
            "q0juu/7",
            "q0juu",//660
            "q2iu/2",
            "q2iu/2",
            "q2iu",
            "q1za/6",
            "q1za/6",//665
            "q1za",
            "q0ypp/4",
            "q0ypp/4",
            "q0ypp",
            "q6zzz/6",//670
            "q6zzz/6",
            "q6zzz",
            "q5yj/5",
            "q5yj/5",
            "q5yj",//675
            "q6qpx/3",
            "q6qpx/3",
            "q6qpx",
            "q5cy/7",
            "q5cy/7",//680
            "q5cy",
            "q3dlu/0",
            "q3dlu/0",
            "q3dlu",
            "q0qz/7",//685
            "q0qz/7",
            "q0qz",
            "q1jmz/3",
            "q1jmz/3",
            "q1jmz",//690
            "q0ply/0",
            "q0ply/0",
            "q0ply",
            "q2zzz/5",
            "q2zzz/5",//695
            "q2zzz",
            "q1jy/4",
            "q1jy/4",
            "q1jy",
            "q8yjy/0",//700
            "q8yjy/0",
            "q8yjy",
            "q9byj/8",
            "q9byj/8",
            "q9byj",//705
            "q3yry/7",
            "q3yry/7",
            "q3yry",
            "q6xqz/8",
            "q6xqz/8",//710
            "q6xqz",
            "q9oz/2",
            "q9oz/2",
            "q9oz",
            "q0lyh/9",//715
            "q0lyh/9",
            "q0lyh",
            "q8ebi/1",
            "q8ebi/1",
            "q8ebi",//720
            "q2eyy/9",
            "q2eyy/9",
            "q2eyy",
            "q7xxw/1",
            "q7xxw/1",//725
            "q7xxw",
            "q8zj/0",
            "q8zj/0",
            "q8zj",
            "q8qb/1",//730
            "q8qb/1",
            "q8qb",
            "q2gq2/5",
            "q2gq2/5",
            "q2gq2",//735
            "q7ujv/5",
            "q7ujv/5",
            "q7ujv",
            "q8pp/5",
            "q8pp/5",//740
            "q8pp",
            "q8yq3/0",
            "q8yq3/0",
            "q8yq3",
            "q2vyz/9",//745
            "q2vyz/9",
            "q2vyz",
            "q7v/6",
            "q7v/6",
            "q7v",//750
            "q9dui/2",
            "q9dui/2",
            "q9dui",
            "q7jpy/4",
            "q7jpy/4",//755
            "q7jpy",
            "q9uzy/6",
            "q9uzy/6",
            "q9uzy",
            "q3dzy/3",//760
            "q3dzy/3",
            "q3dzy",
            "q9xz/5",
            "q9xz/5",
            "q9xz",//765
            "q4qjz/2",
            "q4qjz/2",
            "q4qjz",
            "q3xqu/9",
            "q3xqu/9",//770
            "q3xqu",
            "q8gyf/9",
            "q8gyf/9",
            "q8gyf",
            "q7yqy/0",//775
            "q7yqy/0",
            "q7yqy",
            "q8qk/1",
            "q8qk/1",
            "q8qk",//780
            "q9pn/1",
            "q9pn/1",
            "q9pn",
            "q3zjy/3",
            "q3zjy/3",//785
            "q3zjy",
            "q2q2z/3",
            "q2q2z/3",
            "q2q2z",
            "q0q4j/6",//790
            "q0q4j/6",
            "q0q4j",
            "q9ut/0",
            "q9ut/0",
            "q9ut",//795
            "q8jk/7",
            "q8jk/7",
            "q8jk",
            "q5vq/9",
            "q5vq/9",//800
            "q5vq",
            "q3xj/8",
            "q3xj/8",
            "q3xj",
            "q3pqt/8",//805
            "q3pqt/8",
            "q3pqt",
            "q5q1/8",
            "q5q1/8",
            "q5q1",//810
            "q8xux/5",
            "q8xux/5",
            "q8xux",
            "q2jxy/2",
            "q2jxy/2",//815
            "q2jxy",
            "q4jqx/9",
            "q4jqx/9",
            "q4jqx",
            "q0xyz/2",//820
            "q0xyz/2",
            "q0xyz",
            "q3i/3",
            "q3i/3",
            "q3i",//825
            "q5dxi/3",
            "q5dxi/3",
            "q5dxi",
            "q7yp/5",
            "q7yp/5",//830
            "q7yp",
            "q1yq2/5",
            "q1yq2/5",
            "q1yq2",
            "q0qjp/3",//835
            "q0qjp/3",
            "q0qjp",
            "q2tq3/6",
            "q2tq3/6",
            "q2tq3",//840
            "q4jfq/0",
            "q4jfq/0",
            "q4jfq",
            "q1jqx/7",
            "q1jqx/7",//845
            "q1jqx",
            "q1xqz/9",
            "q1xqz/9",
            "q1xqz",
            "q3z/6",//850
            "q3z/6",
            "q3z",
            "q1jk/2",
            "q1jk/2",
            "q1jk",//855
            "q7jvy/1",
            "q7jvy/1",
            "q7jvy",
            "q3xw/0",
            "q3xw/0",//860
            "q3xw",
            "q4xq/4",
            "q4xq/4",
            "q4xq",
            "q8qcz/3",//865
            "q8qcz/3",
            "q8qcz",
            "q9uxr/5",
            "q9uxr/5",
            "q9uxr",//870
            "q5q4v/7",
            "q5q4v/7",
            "q5q4v",
            "q4xqq/8",
            "q4xqq/8",//875
            "q4xqq",
            "q9qpy/7",
            "q9qpy/7",
            "q9qpy",
            "q0q1/0",//880
            "q0q1/0",
            "q0q1",
            "q9py/6",
            "q9py/6",
            "q9py",//885
            "q0xxp/0",
            "q0xxp/0",
            "q0xxp",
            "q3zx/8",
            "q3zx/8",//890
            "q3zx",
            "q2pjz/0",
            "q2pjz/0",
            "q2pjz",
            "q3q4/8",//895
            "q3q4/8",
            "q3q4",
            "q7ujw/7",
            "q7ujw/7",
            "q7ujw"//900
        });
    }
}
