using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QSO_Trainer.Lister
{
public    class TxNames
    {
        public static List<string> TxName = new List<string>(new string[] {
           "hank",
            "hank",
            "hank",
            "nicholas",
            "nicholas",//5
            "nicholas",
            "bobby",
            "bobby",
            "bobby",
            "becky",//10
            "becky",
            "becky",
            "liza",
            "liza",
            "liza",//15
            "elizabeth",
            "elizabeth",
            "elizabeth",
            "tom",
            "tom",//20
            "tom",
            "daniel",
            "daniel",
            "daniel",
            "jack",//25
            "jack",
            "jack",
            "liza",
            "liza",
            "liza",//30
            "andy",
            "andy",
            "andy",
            "grace",
            "grace",//35
            "grace",
            "johnny",
            "johnny",
            "johnny",
            "alice",//40
            "alice",
            "alice",
            "joe",
            "joe",
            "joe",//45
            "matt",
            "matt",
            "matt",
            "michael",
            "michael",//50
            "michael",
            "sophie",
            "sophie",
            "sophie",
            "matt",//55
            "matt",
            "matt",
            "ann",
            "ann",
            "ann",//60
            "liza",
            "liza",
            "liza",
            "catherine",
            "catherine",//65
            "catherine",
            "ed",
            "ed",
            "ed",
            "joseph",//70
            "joseph",
            "joseph",
            "mickey",
            "mickey",
            "mickey",//75
            "cathy",
            "cathy",
            "cathy",
            "danny",
            "danny",//80
            "danny",
            "vicky",
            "vicky",
            "vicky",
            "john",//85
            "john",
            "john",
            "josh",
            "josh",
            "josh",//90
            "jane",
            "jane",
            "jane",
            "mickey",
            "mickey",//95
            "mickey",
            "sarah",
            "sarah",
            "sarah",
            "hank",//100
            "hank",
            "hank",
            "mary",
            "mary",
            "mary",//105
            "emma",
            "emma",
            "emma",
            "hank",
            "hank",//110
            "hank",
            "emma",
            "emma",
            "emma",
            "liza",//115
            "liza",
            "liza",
            "becky",
            "becky",
            "becky",//120
            "anne",
            "anne",
            "anne",
            "matt",
            "matt",//125
            "matt",
            "samuel",
            "samuel",
            "samuel",
            "jane",//130
            "jane",
            "jane",
            "simon",
            "simon",
            "simon",//135
            "tom",
            "tom",
            "tom",
            "mickey",
            "mickey",//140
            "mickey",
            "danny",
            "danny",
            "danny",
            "andy",//145
            "andy",
            "andy",
            "rachel",
            "rachel",
            "rachel",//150
            "edward",
            "edward",
            "edward",
            "william",
            "william",//155
            "william",
            "bill",
            "bill",
            "bill",
            "jimmy",//160
            "jimmy",
            "jimmy",
            "liza",
            "liza",
            "liza",//165
            "cathy",
            "cathy",
            "cathy",
            "william",
            "william",//170
            "william",
            "hank",
            "hank",
            "hank",
            "julie",//175
            "julie",
            "julie",
            "mary",
            "mary",
            "mary",//180
            "beth",
            "beth",
            "beth",
            "catherine",
            "catherine",//185
            "catherine",
            "mike",
            "mike",
            "mike",
            "simon",//190
            "simon",
            "simon",
            "simon",
            "simon",
            "simon",//195
            "rebecca",
            "rebecca",
            "rebecca",
            "robert",
            "robort",//200
            "robert",
            "grace",
            "grace",
            "grace",
            "vicky",//205
            "vicky",
            "vicky",
            "beth",
            "beth",
            "beth",//210
            "jack",
            "jack",
            "jack",
            "bob",
            "bob",//215
            "bob",
            "lucy",
            "lucy",
            "lucy",
            "pat",//220
            "pat",
            "pat",
            "claire",
            "claire",
            "claire",//225
            "joseph",
            "joseph",
            "joseph",
            "samuel",
            "samuel",//230
            "samuel",
            "michael",
            "michael",
            "michael",
            "rachel",//235
            "rachel",
            "rachel",
            "rachel",
            "rachel",
            "rachel",//240
            "billy",
            "billy",
            "billy",
            "joseph",
            "joseph",//245
            "joseph",
            "dan",
            "dan",
            "dan",
            "dan",//250
            "dan",
            "dan",
            "kate",
            "kate",
            "kate",//255
            "kathy",
            "kathy",
            "kathy",
            "thomas",
            "thomas",//260
            "thomas",
            "vickie",
            "vickie",
            "vickie",
            "emma",//265
            "emma",
            "emma",
            "liza",
            "liza",
            "liza",//270
            "hank",
            "hank",
            "hank",
            "johnny",
            "johnny",//275
            "johnny",
            "david",
            "david",
            "david",
            "thom",//280
            "thom",
            "thom",
            "hank",
            "hank",
            "hank",//285
            "andy",
            "andy",
            "andy",
            "mickey",
            "mickey",//290
            "mickey",
            "pat",
            "pat",
            "pat",
            "billy",//295
            "billy",
            "billy",
            "joe",
            "joe",
            "joe",//300
            "beth",
            "beth",
            "beth",
            "johnny",
            "johnny",//305
            "johnny",
            "simon",
            "simon",
            "simon",
            "becky",//310
            "becky",
            "becky",
            "michael",
            "michael",
            "michael",//315
            "michael",
            "michael",
            "michael",
            "andy",
            "andy",//320
            "andy",
            "liza",
            "liza",
            "liza",
            "rebecca",//325
            "rebecca",
            "rebecca",
            "kate",
            "kate",
            "kate",//330
            "thom",
            "thom",
            "thom",
            "claire",
            "claire",//335
            "claire",
            "joe",
            "joe",
            "joe",
            "catherine",//340
            "catherine",
            "catherine",
            "robert",
            "robert",
            "robert",//345
            "jim",
            "jim",
            "jim",
            "grace",
            "grace",//350
            "grace",
            "rebecca",
            "rebecca",
            "rebecca",
            "johnny",//355
            "johnny",
            "johnny",
            "catherine",
            "catherine",
            "catherine",//360
            "pat",
            "pat",
            "pat",
            "jimmy",
            "jimmy",//365
            "jimmy",
            "johnny",
            "johnny",
            "johnny",
            "nicholas",//370
            "nicholas",
            "nicholas",
            "daniel",
            "daniel",
            "daniel",//375
            "anne",
            "anne",
            "anne",
            "edward",
            "edward",//380
            "edward",
            "johnny",
            "johnny",
            "johnny",
            "jane",//385
            "jane",
            "jane",
            "nick",
            "nick",
            "nick",//390
            "henry",
            "henry",
            "henry",
            "grace",
            "grace",//395
            "grace",
            "kathy",
            "kathy",
            "kathy",
            "mike",//400
            "mike",
            "mike",
            "julie",
            "julie",
            "julie",//405
            "vicky",
            "vicky",
            "vicky",
            "pat",
            "pat",//410
            "pat",
            "william",
            "william",
            "william",
            "bobby",//415
            "bobby",
            "bobby",
            "bob",
            "bob",
            "bob",//420
            "catherine",
            "catherine",
            "catherine",
            "josh",
            "josh",//425
            "josh",
            "beth",
            "beth",
            "beth",
            "bobby",//430
            "bobby",
            "bobby",
            "kathryn",
            "kathryn",
            "kathryn",//435
            "nicholas",
            "nicholas",
            "nicholas",
            "vicky",
            "vicky",//440
            "vicky",
            "jane",
            "jane",
            "jane",
            "mickey",//445
            "mickey",
            "mickey",
            "michael",
            "michael",
            "michael",//450
            "vicky",
            "vicky",
            "vicky",
            "william",
            "william",//455
            "william",
            "bobby",
            "bobby",
            "bobby",
            "alice",//460
            "alice",
            "alice",
            "james",
            "james",
            "james",//465
            "vickie",
            "vickie",
            "vickie",
            "thom",
            "thom",//470
            "thom",
            "daniel",
            "daniel",
            "daniel",
            "bob",//475
            "bob",
            "bob",
            "henry",
            "henry",
            "henry",//480
            "eddie",
            "eddie",
            "eddie",
            "josh",
            "josh",//485
            "josh",
            "jimmy",
            "jimmy",
            "jimmy",
            "joseph",//490
            "joseph",
            "joseph",
            "bobby",
            "bobby",
            "bobby",//495
            "joe",
            "joe",
            "joe",
            "jimmy",
            "jimmy",//500
            "jimmy",
            "mary",
            "mary",
            "mary",
            "laura",//505
            "laura",
            "laura",
            "beth",
            "beth",
            "beth",//510
            "sam",
            "sam",
            "sam",
            "sam",
            "sam",//515
            "sam",
            "daniel",
            "daniel",
            "daniel",
            "eddie",//520
            "eddie",
            "eddie",
            "catherine",
            "catherine",
            "catherine",//525
            "bob",
            "bob",
            "bob",
            "rachel",
            "rachel",//530
            "rachel",
            "rebecca",
            "rebecca",
            "rebecca",
            "matthew",//535
            "matthew",
            "matthew",
            "sarah",
            "sarah",
            "sarah",//540
            "rebecca",
            "rebecca",
            "rebecca",
            "bill",
            "bill",//545
            "bill",
            "michael",
            "michael",
            "michael",
            "mickey",//550
            "mickey",
            "mickey",
            "rachel",
            "rachel",
            "rachel",//555
            "pat",
            "pat",
            "pat",
            "jack",
            "jack",//560
            "jack",
            "kathy",
            "kathy",
            "kathy",
            "laura",//565
            "laura",
            "laura",
            "bob",
            "bob",
            "bob",//570
            "david",
            "david",
            "david",
            "michael",
            "michael",//575
            "michael",
            "kathryn",
            "kathryn",
            "kathryn",
            "danny",//580
            "danny",
            "danny",
            "henry",
            "henry",
            "henry",//585
            "daniel",
            "daniel",
            "daniel",
            "liz",
            "liz",//590
            "liz",
            "becky",
            "becky",
            "becky",
            "sarah",//595
            "sarah",
            "sarah",
            "emma",
            "emma",
            "emma",//600
            "mary",
            "mary",
            "mary",
            "joseph",
            "joseph",//605
            "joseph",
            "patrick",
            "patrick",
            "patrick",
            "john",//610
            "john",
            "john",
            "joe",
            "joe",
            "joe",//615
            "jim",
            "jim",
            "jim",
            "tom",
            "tom",//620
            "tom",
            "emma",
            "emma",
            "emma",
            "eddie",//625
            "eddie",
            "eddie",
            "matthew",
            "matthew",
            "matthew",//630
            "kathryn",
            "kathryn",
            "kathryn",
            "grace",
            "grace",//635
            "grace",
            "joshua",
            "joshua",
            "joshua",
            "eddie",//640
            "eddie",
            "eddie",
            "catherine",
            "catherine",
            "catherine",//645
            "cathy",
            "cathy",
            "cathy",
            "tom",
            "tom",//650
            "tom",
            "liz",
            "liz",
            "liz",
            "john",//655
            "john",
            "john",
            "jim",
            "jim",
            "jim",//660
            "nicholas",
            "nicholas",
            "nicholas",
            "bob",
            "bob",//665
            "bob",
            "vickie",
            "vickie",
            "vickie",
            "david",//670
            "david",
            "david",
            "emma",
            "emma",
            "emma",//675
            "danny",
            "danny",
            "danny",
            "bill",
            "bill",//680
            "bill",
            "simon",
            "simon",
            "simon",
            "joseph",//685
            "joseph",
            "joseph",
            "becky",
            "becky",
            "becky",//690
            "matthew",
            "matthew",
            "matthew",
            "alex",
            "alex",//695
            "alex",
            "alex",
            "alex",
            "alex",
            "grace",//700
            "grace",
            "grace",
            "johnny",
            "johnny",
            "johnny",//705
            "jane",
            "jane",
            "jane",
            "eddie",
            "eddie",//710
            "eddie",
            "jimmy",
            "jimmy",
            "jimmy",
            "julie",//715
            "julie",
            "julie",
            "elizabeth",
            "elizabeth",
            "elizabeth",//720
            "william",
            "william",
            "william",
            "elizabeth",
            "elizabeth",//725
            "elizabeth",
            "david",
            "david",
            "david",
            "dave",//730
            "dave",
            "dave",
            "daniel",
            "daniel",
            "daniel",//735
            "alice",
            "alice",
            "alice",
            "ed",
            "ed",//740
            "ed",
            "matthew",
            "matthew",
            "matthew",
            "billy",//745
            "billy",
            "billy",
            "kathryn",
            "kathryn",
            "kathryn",//750
            "matthew",
            "matthew",
            "matthew",
            "matt",
            "matt",//755
            "matt",
            "nicholas",
            "nicholas",
            "nicholas",
            "kathy",//760
            "kathy",
            "kathy",
            "henry",
            "henry",
            "henry",//765
            "thom",
            "thom",
            "thom",
            "mary",
            "mary",//770
            "mary",
            "patrick",
            "patrick",
            "patrick",
            "andy",//775
            "andy",
            "andy",
            "hank",
            "hank",
            "hank",//780
            "sophie",
            "sophie",
            "sophie",
            "pat",
            "pat",//785
            "pat",
            "robert",
            "robert",
            "robert",
            "catherine",//790
            "catherine",
            "catherine",
            "sarah",
            "sarah",
            "sarah",//795
            "mike",
            "mike",
            "mike",
            "jim",
            "jim",//800
            "jim",
            "becky",
            "becky",
            "becky",
            "ann",//805
            "ann",
            "ann",
            "vicky",
            "vicky",
            "vicky",//810
            "grace",
            "grace",
            "grace",
            "john",
            "john",//815
            "john",
            "lucy",
            "lucy",
            "lucy",
            "liza",//820
            "liza",
            "liza",
            "sarah",
            "sarah",
            "sarah",//825
            "alice",
            "alice",
            "alice",
            "catherine",
            "catherine",//830
            "catherine",
            "james",
            "james",
            "james",
            "william",//835
            "william",
            "william",
            "kate",
            "kate",
            "kate",//840
            "james",
            "james",
            "james",
            "alice",
            "alice",//845
            "alice",
            "vicky",
            "vicky",
            "vicky",
            "becky",//850
            "becky",
            "becky",
            "hank",
            "hank",
            "hank",//855
            "david",
            "david",
            "david",
            "james",
            "james",//860
            "james",
            "bob",
            "bob",
            "bob",
            "andy",//865
            "andy",
            "andy",
            "rebecca",
            "rebecca",
            "rebecca",//870
            "sarah",
            "sarah",
            "sarah",
            "michael",
            "michael",//875
            "michael",
            "nick",
            "nick",
            "nick",
            "dan",//880
            "dan",
            "dan",
            "mike",
            "mike",
            "mike",//885
            "sam",
            "sam",
            "sam",
            "kathy",
            "kathy",//890
            "kathy",
            "cathy",
            "cathy",
            "cathy",
            "henry",//895
            "henry",
            "henry",
            "michael",
            "michael",
            "michael"//900
        });
        
    }
}
